const colors = {
  light: {
    text: "#0D1B2A",
    tint: "#0078C8",
    background: "#F0F4F8",
    foreground: "#0D1B2A",
    card: "#FFFFFF",
    cardForeground: "#0D1B2A",
    primary: "#0078C8",
    primaryForeground: "#FFFFFF",
    secondary: "#E2EBF4",
    secondaryForeground: "#0D1B2A",
    muted: "#E2EBF4",
    mutedForeground: "#5A7A94",
    accent: "#00A87A",
    accentForeground: "#FFFFFF",
    destructive: "#E84040",
    destructiveForeground: "#FFFFFF",
    border: "#C5D9EC",
    input: "#DCEAF5",
    surface: "#FFFFFF",
    surfaceElevated: "#F7FAFD",
  },
  dark: {
    text: "#E8EFF5",
    tint: "#3BA8E8",
    background: "#0D1B2A",
    foreground: "#E8EFF5",
    card: "#1A2B3D",
    cardForeground: "#E8EFF5",
    primary: "#3BA8E8",
    primaryForeground: "#0D1B2A",
    secondary: "#253B52",
    secondaryForeground: "#E8EFF5",
    muted: "#1A2B3D",
    mutedForeground: "#7A9AB5",
    accent: "#00C896",
    accentForeground: "#0D1B2A",
    destructive: "#E84040",
    destructiveForeground: "#FFFFFF",
    border: "#253B52",
    input: "#253B52",
    surface: "#1A2B3D",
    surfaceElevated: "#213347",
  },
  radius: 12,
};

export default colors;
