export type HydraulicsFormulaMapStatus = "mapped_pending_validation";

export interface HydraulicsFormulaMapEntry {
  sourceFile: string;
  sheet: string;
  outputName: string;
  outputCell: string;
  formulaOriginal: string | null;
  inputs: string[];
  dependencies: string[];
  status: HydraulicsFormulaMapStatus;
  notes: string;
}

export const hydraulicsFormulaMap: HydraulicsFormulaMapEntry[] = [
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Pump flow rate",
    outputCell: "C8",
    formulaOriginal: "=(((((0.010199868*(B6^2))*C6)*D6)*C7)/100)",
    inputs: ["B6 camisa", "C6 carrera", "D6 eficiencia_percent", "C7 epm"],
    dependencies: ["ENTRY!B6", "ENTRY!C6", "ENTRY!D6", "ENTRY!C7"],
    status: "mapped_pending_validation",
    notes: "Calcula gasto en gpm desde datos de bomba. Valor observado: 427.41067873139997.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Total flow area",
    outputCell: "C24",
    formulaOriginal: "=((((((((B21^2)+(C21^2))+(D21^2))+(B22^2))+(C22^2))+(D22^2)))/1303.797)",
    inputs: ["B21:D22 nozzle sizes"],
    dependencies: ["ENTRY!B21", "ENTRY!C21", "ENTRY!D21", "ENTRY!B22", "ENTRY!C22", "ENTRY!D22"],
    status: "mapped_pending_validation",
    notes: "TFA en in2 calculada desde diametros de toberas.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Internal string pressure drop",
    outputCell: "U5",
    formulaOriginal: "=CALCULATE!U14",
    inputs: ["mud density", "PV/YP/Fann readings", "flow rate", "tubular OD/ID/length"],
    dependencies: ["CALCULATE!U14"],
    status: "mapped_pending_validation",
    notes: "Salida visible 'Caida de Pres. int. sarta, psi'. CALCULATE!U14 acumula perdidas internas.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Annular pressure drop",
    outputCell: "U6",
    formulaOriginal: "=CALCULATE!R14",
    inputs: ["mud density", "annular rheology", "hole/tubular geometry", "flow rate"],
    dependencies: ["CALCULATE!R14"],
    status: "mapped_pending_validation",
    notes: "Salida visible 'Caida de Pres. Esp. An., psi'. CALCULATE!R14 acumula perdidas anulares.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Bit pressure drop",
    outputCell: "U7",
    formulaOriginal: "=CALCULATE!C20",
    inputs: ["ENTRY!C8 flow rate", "ENTRY!B12 mud density", "ENTRY!B21:D22 nozzle sizes"],
    dependencies: ["CALCULATE!C20"],
    status: "mapped_pending_validation",
    notes: "CALCULATE!C20 usa 156.5 * Q^2 * densidad / TFA^2.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Total pressure drop",
    outputCell: "U8",
    formulaOriginal: "=CALCULATE!C16",
    inputs: ["internal pressure drop", "annular pressure drop", "bit pressure drop"],
    dependencies: ["CALCULATE!R14", "CALCULATE!U14", "CALCULATE!C20"],
    status: "mapped_pending_validation",
    notes: "CALCULATE!C16 = CALCULATE!R14 + CALCULATE!U14 + CALCULATE!C20.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "ECD",
    outputCell: "U9",
    formulaOriginal: "=CALCULATE!S14",
    inputs: ["annular accumulated pressure", "depth", "mud density"],
    dependencies: ["CALCULATE!S14"],
    status: "mapped_pending_validation",
    notes: "Salida visible 'D.E.C. g/cc'. CALCULATE!S14 suma densidad base mas componente de presion anular.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Annular velocities",
    outputCell: "U10:U12",
    formulaOriginal: "=CALCULATE!G11; =IF((A2=1),CALCULATE!G12,\"N/A\"); =CALCULATE!G14",
    inputs: ["flow rate", "hole ID", "tubular OD"],
    dependencies: ["CALCULATE!G11", "CALCULATE!G12", "CALCULATE!G14"],
    status: "mapped_pending_validation",
    notes: "Velocidades anulares en pie/min por intervalo: TP-TR, TP-agujero y DC-agujero.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Volume and lag times",
    outputCell: "U13:U17",
    formulaOriginal: "U13=0.0005067*sum(ID^2*length); U14=0.0005067*annular geometry; U16=(264.2*U13)/C8; U17=(264.2*U14)/C8",
    inputs: ["tubular ID/OD", "hole size", "depth/lengths", "flow rate"],
    dependencies: ["ENTRY!U13", "ENTRY!U14", "ENTRY!C8", "ENTRY!Q7:R22", "ENTRY!D19", "ENTRY!R24"],
    status: "mapped_pending_validation",
    notes: "Agrupa volumen interior, volumen anular, volumen de agujero sin sarta, tiempo de bajada y tiempo de atraso.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "ENTRY",
    outputName: "Cuttings transport and ECD with cuttings",
    outputCell: "U18:U20",
    formulaOriginal: "=CALCULATE!K22; =CALCULATE!K24; =CALCULATE!K25",
    inputs: ["annular velocity", "slip velocity", "cuttings concentration", "base ECD"],
    dependencies: ["CALCULATE!K22", "CALCULATE!K24", "CALCULATE!K25"],
    status: "mapped_pending_validation",
    notes: "Eficiencia de transporte, concentracion de cortes y DEC con cortes.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "CALCULATE",
    outputName: "Power-law rheology parameters",
    outputCell: "B5:B6,F5:F6",
    formulaOriginal: "B5=0.5*LOG10((C12+D12)/C13); B6=5.11*(C12+D12)/(511^B5); F5=3.32*LOG10(((C12+D12)+C12)/(C12+D12)); F6=5.11*((2*C12)+D12)/(1022^F5)",
    inputs: ["ENTRY!C12 PV", "ENTRY!D12 yield point", "ENTRY!C13 Fann 3 rpm"],
    dependencies: ["ENTRY!C12", "ENTRY!D12", "ENTRY!C13", "CALCULATE!B5", "CALCULATE!F5"],
    status: "mapped_pending_validation",
    notes: "n/K anular y n/K interno usados por Reynolds, viscosidad efectiva y factores de friccion.",
  },
  {
    sourceFile: "HIDRAULICA_RIVERO.xls",
    sheet: "CALCULATE",
    outputName: "Interval hydraulic calculations",
    outputCell: "G11:U14",
    formulaOriginal: "Velocity=24.48*Q/(Dh^2-OD^2) or 24.48*Q/ID^2; Re, friction factor, pressure loss and ECD are calculated per interval.",
    inputs: ["CALCULATE!B4 flow rate", "ENTRY!B12 mud density", "CALCULATE!B5:B6", "CALCULATE!F5:F6", "interval geometry C:F"],
    dependencies: ["CALCULATE!G11:U14", "ENTRY!B12"],
    status: "mapped_pending_validation",
    notes: "Tabla por intervalo: velocidades, viscosidades efectivas, Reynolds, regimen, friccion, caida de presion anular/interior y ECD.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Consol",
    outputName: "Chosen string pressure losses",
    outputCell: "F3",
    formulaOriginal: "=IF((NAME=1),C3,IF((NAME=2),D3,E3))",
    inputs: ["rheology model selector", "BP!AC37", "PL!AK37"],
    dependencies: ["Consol!C3", "Consol!D3", "Consol!E3", "BP!AC37", "PL!AK37"],
    status: "mapped_pending_validation",
    notes: "Selecciona perdidas internas de sarta entre modelos BP, PL y HB. NAME representa un nombre definido no resuelto por el lector BIFF.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Consol",
    outputName: "Chosen annular pressure losses",
    outputCell: "F4",
    formulaOriginal: "=IF((NAME=1),C4,IF((NAME=2),D4,E4))",
    inputs: ["rheology model selector", "BP!Q38", "PL!T38"],
    dependencies: ["Consol!C4", "Consol!D4", "Consol!E4", "BP!Q38", "PL!T38"],
    status: "mapped_pending_validation",
    notes: "Selecciona perdidas anulares entre modelos BP, PL y HB.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Consol",
    outputName: "Surface equipment pressure loss",
    outputCell: "C10:C15",
    formulaOriginal: "C10:C13 use ((0.7293*(MW/8.33)+0.2826)*MW^0.2*coefficient*Q^1.8039)/6.8947; C15 selects equipment type 1-4.",
    inputs: ["flow rate", "mud weight", "surface equipment type"],
    dependencies: ["Consol!C10", "Consol!C11", "Consol!C12", "Consol!C13"],
    status: "mapped_pending_validation",
    notes: "Coeficientes detectados por tipo: 0.0095, 0.0037, 0.0019 y 0.0015.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Consol",
    outputName: "MWD and PDM pressure drops",
    outputCell: "C16:C17",
    formulaOriginal: "=Input!H22; =Input!H23",
    inputs: ["Main!D16 pressure drop MWD", "Main!D17 pressure drop PDM"],
    dependencies: ["Input!H22", "Input!H23"],
    status: "mapped_pending_validation",
    notes: "Perdidas adicionales importadas desde Input, que a su vez convierte unidades desde Main.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Consol",
    outputName: "Bit TFA",
    outputCell: "C19",
    formulaOriginal: "=(sum(nozzle_diameter^2)*PI())/4096",
    inputs: ["Main!K12:K20 nozzle diameters"],
    dependencies: ["Consol!C19"],
    status: "mapped_pending_validation",
    notes: "Formula decodificada parcialmente: el lector preserva algunos nombres definidos como NAME.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Consol",
    outputName: "Bit pressure loss",
    outputCell: "C20",
    formulaOriginal: "=(((156.5*(FlowRate^2))*MudWeight)/(TFA^2))",
    inputs: ["flow rate", "mud weight", "TFA"],
    dependencies: ["Consol!C20", "Consol!C19"],
    status: "mapped_pending_validation",
    notes: "Misma familia de formula que Rivero para perdida de presion en barrena.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Consol",
    outputName: "Bit hydraulics",
    outputCell: "C21:C25",
    formulaOriginal: "HHP=(BitPressureLoss*FlowRate)/1714; HSI=(HHP*1.27)/(BitSize^2); JetVelocity=(417.2*FlowRate)/TFA; ImpactForce=(FlowRate*JetVelocity*MudWeight)/1930; IF/area=(ImpactForce*1.27)/(BitSize^2)",
    inputs: ["bit pressure loss", "flow rate", "TFA", "bit size", "mud weight"],
    dependencies: ["Consol!C20", "Consol!C21", "Consol!C22", "Consol!C23", "Consol!C24", "Consol!C25"],
    status: "mapped_pending_validation",
    notes: "Agrupa HHP bit, HSI, velocidad de chorro, fuerza de impacto e impacto por area.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Consol",
    outputName: "Total system pressure and hydraulic power",
    outputCell: "C26:C28",
    formulaOriginal: "TotalSystemPressure=sum(surface, MWD, PDM, string, annular, bit); PercentBit=(BitPressureLoss/C26)*100; SystemHHP=(TotalSystemPressure*FlowRate)/1714",
    inputs: ["surface losses", "MWD/PDM losses", "string losses", "annular losses", "bit pressure loss", "flow rate"],
    dependencies: ["Consol!C15", "Consol!C16", "Consol!C17", "Consol!F3", "Consol!F4", "Consol!C20", "Consol!C26"],
    status: "mapped_pending_validation",
    notes: "Resumen de presion total del sistema y potencia hidraulica del sistema.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Output",
    outputName: "Public output conversions",
    outputCell: "D4:D18,N4:N33",
    formulaOriginal: "D/N columns convert base psi, ppg, ft/sec, HP and force values according to selected unit names.",
    inputs: ["Consol outputs", "unit selectors", "rheology model selector"],
    dependencies: ["Output!C4:C18", "Output!M4:M33", "Consol!N3:N33"],
    status: "mapped_pending_validation",
    notes: "Output es una capa de presentacion/calculo que convierte unidades; no debe usarse aun para desbloquear hydraulics.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "Input",
    outputName: "Normalized workbook inputs",
    outputCell: "H11:H24,K11:K21,C17:D35",
    formulaOriginal: "Input converts Main/Setup values into normalized calculation units for BP, PL and Consol.",
    inputs: ["Main flow rate", "Main mud weight", "Main Fann readings", "Main nozzle sizes", "Setup geometry"],
    dependencies: ["Main!D8", "Main!D11", "Main!D16:D17", "Main!D21", "Main!D25:D30", "Main!K12:K21", "Setup!E8:R12", "Setup!G24"],
    status: "mapped_pending_validation",
    notes: "Hoja puente: detecta geometria efectiva, longitudes, densidad, reologia, toberas y perdidas extra.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "BP",
    outputName: "Bingham Plastic pressure model",
    outputCell: "Q38,AC37,AE13:AE35",
    formulaOriginal: "BP sheet calculates annular/internal pressure losses, flow regime, actual annular velocity, critical annular velocity and critical flow rate by segment.",
    inputs: ["Input normalized geometry", "flow rate", "mud weight", "Bingham PV", "Bingham YP"],
    dependencies: ["Input", "BP!Q38", "BP!AC37", "BP!AE13:AE35"],
    status: "mapped_pending_validation",
    notes: "Contiene 576 formulas. Mapa pendiente de validacion numerica por celdas representativas.",
  },
  {
    sourceFile: "Hydraulics_IPM.xls",
    sheet: "PL",
    outputName: "Power Law pressure model",
    outputCell: "T38,AK37,AM13:AM35",
    formulaOriginal: "PL sheet calculates annular/internal pressure losses, flow regime, actual annular velocity, critical annular velocity and critical flow rate by segment.",
    inputs: ["Input normalized geometry", "flow rate", "mud weight", "Power Law n", "Power Law K"],
    dependencies: ["Input", "PL!T38", "PL!AK37", "PL!AM13:AM35"],
    status: "mapped_pending_validation",
    notes: "Contiene 744 formulas. Mapa pendiente de validacion numerica por celdas representativas.",
  },
];

export default hydraulicsFormulaMap;
